name: Bot Relatorio PowerBI

on:
  schedule:
    - cron: '0 11 * * 1-5' # Roda de segunda a sexta às 08:00 (Horário de Brasília)
  workflow_dispatch: # Ativa o botão de rodar manualmente

jobs:
  rodar-automacao:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
      - name: 1. Puxar arquivos do repositorio
        uses: actions/checkout@v4

      - name: 2. Instalar o ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Instalar dependencias
        run: pip install selenium

      - name: 4. Executar o Script Python com Caixa-Preta
        env:
          SENHA_EMAIL: ${{ secrets.SENHA_EMAIL }}
        run: python relatorio_salesco.py
