name: Bot Relatorio PowerBI

on:
  schedule:
    - cron: '0 11 * * 1-5'
  workflow_dispatch:

jobs:
  rodar-automacao:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

    steps:
      - name: 1. Puxar arquivos do repositorio
        uses: actions/checkout@v4

      - name: 2. Verificar arquivos e versões do sistema (Auditoria)
        run: |
          echo "=== Lista de Arquivos no Servidor ==="
          ls -la
          echo "=== Versão do Google Chrome Nativo ==="
          google-chrome --version

      - name: 3. Instalar o ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 4. Instalar dependencias
        run: pip install selenium

      - name: 5. Executar o Script Python com Caixa-Preta
        env:
          SENHA_EMAIL: ${{ secrets.SENHA_EMAIL }}
        run: python relatorio_salesco.py
